
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COLOR_TEXTO_BLOQUE = 23;
  public static final int LETRA_SIZE_MIENTRAS = 22;
  public static final int ENTERO = 57;
  public static final int SI = 4;
  public static final int MOSTRAR = 8;
  public static final int FIGURA_BLOQUE = 25;
  public static final int DIFERENTE = 46;
  public static final int LETRA_MIENTRAS = 21;
  public static final int ENTONCES = 5;
  public static final int RECTANGULO_REDONDEADO = 33;
  public static final int PARENTESIS_ABIERTO = 38;
  public static final int SEPARADOR = 11;
  public static final int FIN = 3;
  public static final int MULTIPLICADO = 42;
  public static final int NOT = 53;
  public static final int AND = 51;
  public static final int IGUAL = 44;
  public static final int DIVIDIDO = 43;
  public static final int OR = 52;
  public static final int MIENTRAS = 6;
  public static final int LETRA_SIZE_BLOQUE = 27;
  public static final int ARIAL = 34;
  public static final int CIRCULO = 29;
  public static final int ID = 59;
  public static final int IGUAL_IGUAL = 45;
  public static final int COLOR_HEX = 60;
  public static final int DECIMAL = 58;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 54;
  public static final int COLOR_BLOQUE = 24;
  public static final int CADENA = 56;
  public static final int PIPE = 55;
  public static final int COMIC_SANS = 36;
  public static final int MENOS = 41;
  public static final int MENOR = 47;
  public static final int COLOR_MIENTRAS = 19;
  public static final int COLOR_TEXTO_MIENTRAS = 18;
  public static final int VERDANA = 37;
  public static final int LETRA_BLOQUE = 26;
  public static final int TIMES_NEW_ROMAN = 35;
  public static final int MAYOR = 48;
  public static final int ELIPSE = 28;
  public static final int ROMBO = 32;
  public static final int RECTANGULO = 31;
  public static final int FIGURA_MIENTRAS = 20;
  public static final int MAYOR_IGUAL = 50;
  public static final int DEFAULT = 12;
  public static final int LEER = 9;
  public static final int HACER = 7;
  public static final int PARENTESIS_CERRADO = 39;
  public static final int COLOR_SI = 14;
  public static final int LETRA_SI = 16;
  public static final int PARALELOGRAMO = 30;
  public static final int INICIO = 2;
  public static final int MENOR_IGUAL = 49;
  public static final int COLOR_TEXTO_SI = 13;
  public static final int FIGURA_SI = 15;
  public static final int VAR = 10;
  public static final int MAS = 40;
  public static final int LETRA_SIZE_SI = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "SI",
  "ENTONCES",
  "MIENTRAS",
  "HACER",
  "MOSTRAR",
  "LEER",
  "VAR",
  "SEPARADOR",
  "DEFAULT",
  "COLOR_TEXTO_SI",
  "COLOR_SI",
  "FIGURA_SI",
  "LETRA_SI",
  "LETRA_SIZE_SI",
  "COLOR_TEXTO_MIENTRAS",
  "COLOR_MIENTRAS",
  "FIGURA_MIENTRAS",
  "LETRA_MIENTRAS",
  "LETRA_SIZE_MIENTRAS",
  "COLOR_TEXTO_BLOQUE",
  "COLOR_BLOQUE",
  "FIGURA_BLOQUE",
  "LETRA_BLOQUE",
  "LETRA_SIZE_BLOQUE",
  "ELIPSE",
  "CIRCULO",
  "PARALELOGRAMO",
  "RECTANGULO",
  "ROMBO",
  "RECTANGULO_REDONDEADO",
  "ARIAL",
  "TIMES_NEW_ROMAN",
  "COMIC_SANS",
  "VERDANA",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "MAS",
  "MENOS",
  "MULTIPLICADO",
  "DIVIDIDO",
  "IGUAL",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "COMA",
  "PIPE",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "ID",
  "COLOR_HEX"
  };
}

