
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.aplicacioncompi1.uitheme.logic;

import java_cup.runtime.*;
import java.util.*;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\101\000\002\002\004\000\002\002\003\000\002\002" +
    "\005\000\002\003\005\000\002\004\004\000\002\004\003" +
    "\000\002\005\006\000\002\005\005\000\002\005\004\000" +
    "\002\005\004\000\002\005\004\000\002\005\012\000\002" +
    "\005\012\000\002\006\005\000\002\006\005\000\002\006" +
    "\005\000\002\006\005\000\002\006\005\000\002\006\005" +
    "\000\002\006\005\000\002\006\005\000\002\006\004\000" +
    "\002\006\005\000\002\007\005\000\002\007\005\000\002" +
    "\007\003\000\002\010\005\000\002\010\005\000\002\010" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\011\005\000\002\012\003\000\002\013\004\000" +
    "\002\013\003\000\002\014\005\000\002\014\007\000\002" +
    "\014\007\000\002\014\007\000\002\014\007\000\002\014" +
    "\007\000\002\014\007\000\002\014\007\000\002\014\007" +
    "\000\002\014\007\000\002\014\007\000\002\014\007\000" +
    "\002\014\007\000\002\014\007\000\002\014\007\000\002" +
    "\014\007\000\002\015\003\000\002\015\003\000\002\016" +
    "\007\000\002\017\003\000\002\017\003\000\002\017\003" +
    "\000\002\017\003\000\002\017\003\000\002\017\003\000" +
    "\002\020\003\000\002\020\003\000\002\020\003\000\002" +
    "\020\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\260\000\004\004\005\001\002\000\004\002\262\001" +
    "\002\000\016\006\176\010\202\012\200\013\175\014\173" +
    "\075\174\001\002\000\006\002\000\015\007\001\002\000" +
    "\042\016\030\017\023\020\027\021\020\022\012\023\010" +
    "\024\025\025\017\026\026\027\024\030\015\031\011\032" +
    "\016\033\032\034\013\035\022\001\002\000\004\056\167" +
    "\001\002\000\004\056\163\001\002\000\004\056\157\001" +
    "\002\000\004\056\153\001\002\000\044\002\uffe0\016\030" +
    "\017\023\020\027\021\020\022\012\023\010\024\025\025" +
    "\017\026\026\027\024\030\015\031\011\032\016\033\032" +
    "\034\013\035\022\001\002\000\004\056\146\001\002\000" +
    "\004\056\142\001\002\000\004\056\136\001\002\000\004" +
    "\056\132\001\002\000\004\002\uffff\001\002\000\004\056" +
    "\126\001\002\000\004\056\122\001\002\000\004\056\112" +
    "\001\002\000\004\056\106\001\002\000\004\056\102\001" +
    "\002\000\004\056\067\001\002\000\004\056\065\001\002" +
    "\000\044\002\uffde\016\uffde\017\uffde\020\uffde\021\uffde\022" +
    "\uffde\023\uffde\024\uffde\025\uffde\026\uffde\027\uffde\030\uffde" +
    "\031\uffde\032\uffde\033\uffde\034\uffde\035\uffde\001\002\000" +
    "\004\056\033\001\002\000\016\036\041\037\040\040\037" +
    "\041\034\042\042\043\036\001\002\000\004\071\uffc7\001" +
    "\002\000\004\071\043\001\002\000\004\071\uffc5\001\002" +
    "\000\004\071\uffc8\001\002\000\004\071\uffc9\001\002\000" +
    "\004\071\uffca\001\002\000\004\071\uffc6\001\002\000\012" +
    "\050\046\073\050\074\047\075\044\001\002\000\120\002" +
    "\uffe2\005\uffe2\006\uffe2\010\uffe2\012\uffe2\013\uffe2\014\uffe2" +
    "\016\uffe2\017\uffe2\020\uffe2\021\uffe2\022\uffe2\023\uffe2\024" +
    "\uffe2\025\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2\032\uffe2" +
    "\033\uffe2\034\uffe2\035\uffe2\051\uffe2\052\uffe2\053\uffe2\054" +
    "\uffe2\055\uffe2\057\uffe2\060\uffe2\061\uffe2\062\uffe2\063\uffe2" +
    "\064\uffe2\065\uffe2\066\uffe2\070\uffe2\071\uffe2\075\uffe2\001" +
    "\002\000\120\002\uffe5\005\uffe5\006\uffe5\010\uffe5\012\uffe5" +
    "\013\uffe5\014\uffe5\016\uffe5\017\uffe5\020\uffe5\021\uffe5\022" +
    "\uffe5\023\uffe5\024\uffe5\025\uffe5\026\uffe5\027\uffe5\030\uffe5" +
    "\031\uffe5\032\uffe5\033\uffe5\034\uffe5\035\uffe5\051\uffe5\052" +
    "\uffe5\053\uffe5\054\uffe5\055\uffe5\057\uffe5\060\uffe5\061\uffe5" +
    "\062\uffe5\063\uffe5\064\uffe5\065\uffe5\066\uffe5\070\uffe5\071" +
    "\uffe5\075\uffe5\001\002\000\012\050\046\073\050\074\047" +
    "\075\044\001\002\000\120\002\uffe3\005\uffe3\006\uffe3\010" +
    "\uffe3\012\uffe3\013\uffe3\014\uffe3\016\uffe3\017\uffe3\020\uffe3" +
    "\021\uffe3\022\uffe3\023\uffe3\024\uffe3\025\uffe3\026\uffe3\027" +
    "\uffe3\030\uffe3\031\uffe3\032\uffe3\033\uffe3\034\uffe3\035\uffe3" +
    "\051\uffe3\052\uffe3\053\uffe3\054\uffe3\055\uffe3\057\uffe3\060" +
    "\uffe3\061\uffe3\062\uffe3\063\uffe3\064\uffe3\065\uffe3\066\uffe3" +
    "\070\uffe3\071\uffe3\075\uffe3\001\002\000\120\002\uffe4\005" +
    "\uffe4\006\uffe4\010\uffe4\012\uffe4\013\uffe4\014\uffe4\016\uffe4" +
    "\017\uffe4\020\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025" +
    "\uffe4\026\uffe4\027\uffe4\030\uffe4\031\uffe4\032\uffe4\033\uffe4" +
    "\034\uffe4\035\uffe4\051\uffe4\052\uffe4\053\uffe4\054\uffe4\055" +
    "\uffe4\057\uffe4\060\uffe4\061\uffe4\062\uffe4\063\uffe4\064\uffe4" +
    "\065\uffe4\066\uffe4\070\uffe4\071\uffe4\075\uffe4\001\002\000" +
    "\050\002\uffd0\016\uffd0\017\uffd0\020\uffd0\021\uffd0\022\uffd0" +
    "\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030\uffd0\031" +
    "\uffd0\032\uffd0\033\uffd0\034\uffd0\035\uffd0\052\057\053\060" +
    "\001\002\000\120\002\uffe8\005\uffe8\006\uffe8\010\uffe8\012" +
    "\uffe8\013\uffe8\014\uffe8\016\uffe8\017\uffe8\020\uffe8\021\uffe8" +
    "\022\uffe8\023\uffe8\024\uffe8\025\uffe8\026\uffe8\027\uffe8\030" +
    "\uffe8\031\uffe8\032\uffe8\033\uffe8\034\uffe8\035\uffe8\051\uffe8" +
    "\052\uffe8\053\uffe8\054\053\055\054\057\uffe8\060\uffe8\061" +
    "\uffe8\062\uffe8\063\uffe8\064\uffe8\065\uffe8\066\uffe8\070\uffe8" +
    "\071\uffe8\075\uffe8\001\002\000\012\050\046\073\050\074" +
    "\047\075\044\001\002\000\012\050\046\073\050\074\047" +
    "\075\044\001\002\000\120\002\uffe6\005\uffe6\006\uffe6\010" +
    "\uffe6\012\uffe6\013\uffe6\014\uffe6\016\uffe6\017\uffe6\020\uffe6" +
    "\021\uffe6\022\uffe6\023\uffe6\024\uffe6\025\uffe6\026\uffe6\027" +
    "\uffe6\030\uffe6\031\uffe6\032\uffe6\033\uffe6\034\uffe6\035\uffe6" +
    "\051\uffe6\052\uffe6\053\uffe6\054\uffe6\055\uffe6\057\uffe6\060" +
    "\uffe6\061\uffe6\062\uffe6\063\uffe6\064\uffe6\065\uffe6\066\uffe6" +
    "\070\uffe6\071\uffe6\075\uffe6\001\002\000\120\002\uffe7\005" +
    "\uffe7\006\uffe7\010\uffe7\012\uffe7\013\uffe7\014\uffe7\016\uffe7" +
    "\017\uffe7\020\uffe7\021\uffe7\022\uffe7\023\uffe7\024\uffe7\025" +
    "\uffe7\026\uffe7\027\uffe7\030\uffe7\031\uffe7\032\uffe7\033\uffe7" +
    "\034\uffe7\035\uffe7\051\uffe7\052\uffe7\053\uffe7\054\uffe7\055" +
    "\uffe7\057\uffe7\060\uffe7\061\uffe7\062\uffe7\063\uffe7\064\uffe7" +
    "\065\uffe7\066\uffe7\070\uffe7\071\uffe7\075\uffe7\001\002\000" +
    "\012\050\046\073\050\074\047\075\044\001\002\000\012" +
    "\050\046\073\050\074\047\075\044\001\002\000\120\002" +
    "\uffe9\005\uffe9\006\uffe9\010\uffe9\012\uffe9\013\uffe9\014\uffe9" +
    "\016\uffe9\017\uffe9\020\uffe9\021\uffe9\022\uffe9\023\uffe9\024" +
    "\uffe9\025\uffe9\026\uffe9\027\uffe9\030\uffe9\031\uffe9\032\uffe9" +
    "\033\uffe9\034\uffe9\035\uffe9\051\uffe9\052\uffe9\053\uffe9\054" +
    "\053\055\054\057\uffe9\060\uffe9\061\uffe9\062\uffe9\063\uffe9" +
    "\064\uffe9\065\uffe9\066\uffe9\070\uffe9\071\uffe9\075\uffe9\001" +
    "\002\000\120\002\uffea\005\uffea\006\uffea\010\uffea\012\uffea" +
    "\013\uffea\014\uffea\016\uffea\017\uffea\020\uffea\021\uffea\022" +
    "\uffea\023\uffea\024\uffea\025\uffea\026\uffea\027\uffea\030\uffea" +
    "\031\uffea\032\uffea\033\uffea\034\uffea\035\uffea\051\uffea\052" +
    "\uffea\053\uffea\054\053\055\054\057\uffea\060\uffea\061\uffea" +
    "\062\uffea\063\uffea\064\uffea\065\uffea\066\uffea\070\uffea\071" +
    "\uffea\075\uffea\001\002\000\010\051\064\052\057\053\060" +
    "\001\002\000\120\002\uffe1\005\uffe1\006\uffe1\010\uffe1\012" +
    "\uffe1\013\uffe1\014\uffe1\016\uffe1\017\uffe1\020\uffe1\021\uffe1" +
    "\022\uffe1\023\uffe1\024\uffe1\025\uffe1\026\uffe1\027\uffe1\030" +
    "\uffe1\031\uffe1\032\uffe1\033\uffe1\034\uffe1\035\uffe1\051\uffe1" +
    "\052\uffe1\053\uffe1\054\uffe1\055\uffe1\057\uffe1\060\uffe1\061" +
    "\uffe1\062\uffe1\063\uffe1\064\uffe1\065\uffe1\066\uffe1\070\uffe1" +
    "\071\uffe1\075\uffe1\001\002\000\012\050\046\073\050\074" +
    "\047\075\044\001\002\000\050\002\uffdd\016\uffdd\017\uffdd" +
    "\020\uffdd\021\uffdd\022\uffdd\023\uffdd\024\uffdd\025\uffdd\026" +
    "\uffdd\027\uffdd\030\uffdd\031\uffdd\032\uffdd\033\uffdd\034\uffdd" +
    "\035\uffdd\052\057\053\060\001\002\000\014\050\046\073" +
    "\050\074\047\075\044\076\070\001\002\000\004\071\uffcd" +
    "\001\002\000\004\071\100\001\002\000\010\052\057\053" +
    "\060\070\074\001\002\000\004\071\uffcc\001\002\000\012" +
    "\050\046\073\050\074\047\075\044\001\002\000\010\052" +
    "\057\053\060\070\076\001\002\000\012\050\046\073\050" +
    "\074\047\075\044\001\002\000\010\052\057\053\060\071" +
    "\uffcb\001\002\000\012\050\046\073\050\074\047\075\044" +
    "\001\002\000\050\002\uffdb\016\uffdb\017\uffdb\020\uffdb\021" +
    "\uffdb\022\uffdb\023\uffdb\024\uffdb\025\uffdb\026\uffdb\027\uffdb" +
    "\030\uffdb\031\uffdb\032\uffdb\033\uffdb\034\uffdb\035\uffdb\052" +
    "\057\053\060\001\002\000\016\036\041\037\040\040\037" +
    "\041\034\042\042\043\036\001\002\000\004\071\104\001" +
    "\002\000\012\050\046\073\050\074\047\075\044\001\002" +
    "\000\050\002\uffd5\016\uffd5\017\uffd5\020\uffd5\021\uffd5\022" +
    "\uffd5\023\uffd5\024\uffd5\025\uffd5\026\uffd5\027\uffd5\030\uffd5" +
    "\031\uffd5\032\uffd5\033\uffd5\034\uffd5\035\uffd5\052\057\053" +
    "\060\001\002\000\014\050\046\073\050\074\047\075\044" +
    "\076\070\001\002\000\004\071\110\001\002\000\012\050" +
    "\046\073\050\074\047\075\044\001\002\000\050\002\uffd7" +
    "\016\uffd7\017\uffd7\020\uffd7\021\uffd7\022\uffd7\023\uffd7\024" +
    "\uffd7\025\uffd7\026\uffd7\027\uffd7\030\uffd7\031\uffd7\032\uffd7" +
    "\033\uffd7\034\uffd7\035\uffd7\052\057\053\060\001\002\000" +
    "\012\044\115\045\117\046\114\047\116\001\002\000\004" +
    "\071\120\001\002\000\004\071\uffc2\001\002\000\004\071" +
    "\uffc4\001\002\000\004\071\uffc1\001\002\000\004\071\uffc3" +
    "\001\002\000\012\050\046\073\050\074\047\075\044\001" +
    "\002\000\050\002\uffd4\016\uffd4\017\uffd4\020\uffd4\021\uffd4" +
    "\022\uffd4\023\uffd4\024\uffd4\025\uffd4\026\uffd4\027\uffd4\030" +
    "\uffd4\031\uffd4\032\uffd4\033\uffd4\034\uffd4\035\uffd4\052\057" +
    "\053\060\001\002\000\014\050\046\073\050\074\047\075" +
    "\044\076\070\001\002\000\004\071\124\001\002\000\012" +
    "\050\046\073\050\074\047\075\044\001\002\000\050\002" +
    "\uffdc\016\uffdc\017\uffdc\020\uffdc\021\uffdc\022\uffdc\023\uffdc" +
    "\024\uffdc\025\uffdc\026\uffdc\027\uffdc\030\uffdc\031\uffdc\032" +
    "\uffdc\033\uffdc\034\uffdc\035\uffdc\052\057\053\060\001\002" +
    "\000\012\050\046\073\050\074\047\075\044\001\002\000" +
    "\010\052\057\053\060\071\130\001\002\000\012\050\046" +
    "\073\050\074\047\075\044\001\002\000\050\002\uffce\016" +
    "\uffce\017\uffce\020\uffce\021\uffce\022\uffce\023\uffce\024\uffce" +
    "\025\uffce\026\uffce\027\uffce\030\uffce\031\uffce\032\uffce\033" +
    "\uffce\034\uffce\035\uffce\052\057\053\060\001\002\000\016" +
    "\036\041\037\040\040\037\041\034\042\042\043\036\001" +
    "\002\000\004\071\134\001\002\000\012\050\046\073\050" +
    "\074\047\075\044\001\002\000\050\002\uffda\016\uffda\017" +
    "\uffda\020\uffda\021\uffda\022\uffda\023\uffda\024\uffda\025\uffda" +
    "\026\uffda\027\uffda\030\uffda\031\uffda\032\uffda\033\uffda\034" +
    "\uffda\035\uffda\052\057\053\060\001\002\000\014\050\046" +
    "\073\050\074\047\075\044\076\070\001\002\000\004\071" +
    "\140\001\002\000\012\050\046\073\050\074\047\075\044" +
    "\001\002\000\050\002\uffd6\016\uffd6\017\uffd6\020\uffd6\021" +
    "\uffd6\022\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027\uffd6" +
    "\030\uffd6\031\uffd6\032\uffd6\033\uffd6\034\uffd6\035\uffd6\052" +
    "\057\053\060\001\002\000\014\050\046\073\050\074\047" +
    "\075\044\076\070\001\002\000\004\071\144\001\002\000" +
    "\012\050\046\073\050\074\047\075\044\001\002\000\050" +
    "\002\uffd1\016\uffd1\017\uffd1\020\uffd1\021\uffd1\022\uffd1\023" +
    "\uffd1\024\uffd1\025\uffd1\026\uffd1\027\uffd1\030\uffd1\031\uffd1" +
    "\032\uffd1\033\uffd1\034\uffd1\035\uffd1\052\057\053\060\001" +
    "\002\000\012\050\046\073\050\074\047\075\044\001\002" +
    "\000\010\052\057\053\060\071\150\001\002\000\012\050" +
    "\046\073\050\074\047\075\044\001\002\000\050\002\uffd3" +
    "\016\uffd3\017\uffd3\020\uffd3\021\uffd3\022\uffd3\023\uffd3\024" +
    "\uffd3\025\uffd3\026\uffd3\027\uffd3\030\uffd3\031\uffd3\032\uffd3" +
    "\033\uffd3\034\uffd3\035\uffd3\052\057\053\060\001\002\000" +
    "\044\002\uffdf\016\uffdf\017\uffdf\020\uffdf\021\uffdf\022\uffdf" +
    "\023\uffdf\024\uffdf\025\uffdf\026\uffdf\027\uffdf\030\uffdf\031" +
    "\uffdf\032\uffdf\033\uffdf\034\uffdf\035\uffdf\001\002\000\012" +
    "\044\115\045\117\046\114\047\116\001\002\000\004\071" +
    "\155\001\002\000\012\050\046\073\050\074\047\075\044" +
    "\001\002\000\050\002\uffcf\016\uffcf\017\uffcf\020\uffcf\021" +
    "\uffcf\022\uffcf\023\uffcf\024\uffcf\025\uffcf\026\uffcf\027\uffcf" +
    "\030\uffcf\031\uffcf\032\uffcf\033\uffcf\034\uffcf\035\uffcf\052" +
    "\057\053\060\001\002\000\012\044\115\045\117\046\114" +
    "\047\116\001\002\000\004\071\161\001\002\000\012\050" +
    "\046\073\050\074\047\075\044\001\002\000\050\002\uffd9" +
    "\016\uffd9\017\uffd9\020\uffd9\021\uffd9\022\uffd9\023\uffd9\024" +
    "\uffd9\025\uffd9\026\uffd9\027\uffd9\030\uffd9\031\uffd9\032\uffd9" +
    "\033\uffd9\034\uffd9\035\uffd9\052\057\053\060\001\002\000" +
    "\014\050\046\073\050\074\047\075\044\076\070\001\002" +
    "\000\004\071\165\001\002\000\012\050\046\073\050\074" +
    "\047\075\044\001\002\000\050\002\uffd2\016\uffd2\017\uffd2" +
    "\020\uffd2\021\uffd2\022\uffd2\023\uffd2\024\uffd2\025\uffd2\026" +
    "\uffd2\027\uffd2\030\uffd2\031\uffd2\032\uffd2\033\uffd2\034\uffd2" +
    "\035\uffd2\052\057\053\060\001\002\000\012\050\046\073" +
    "\050\074\047\075\044\001\002\000\010\052\057\053\060" +
    "\071\171\001\002\000\012\050\046\073\050\074\047\075" +
    "\044\001\002\000\050\002\uffd8\016\uffd8\017\uffd8\020\uffd8" +
    "\021\uffd8\022\uffd8\023\uffd8\024\uffd8\025\uffd8\026\uffd8\027" +
    "\uffd8\030\uffd8\031\uffd8\032\uffd8\033\uffd8\034\uffd8\035\uffd8" +
    "\052\057\053\060\001\002\000\004\075\257\001\002\000" +
    "\004\056\255\001\002\000\004\075\254\001\002\000\004" +
    "\050\245\001\002\000\020\005\244\006\176\010\202\012" +
    "\200\013\175\014\173\075\174\001\002\000\006\072\243" +
    "\075\242\001\002\000\020\005\ufffc\006\ufffc\010\ufffc\012" +
    "\ufffc\013\ufffc\014\ufffc\075\ufffc\001\002\000\004\050\203" +
    "\001\002\000\014\050\206\067\207\073\050\074\047\075" +
    "\044\001\002\000\022\052\057\053\060\057\221\060\224" +
    "\061\220\062\223\063\225\064\222\001\002\000\010\051" +
    "\234\065\211\066\212\001\002\000\014\050\206\067\207" +
    "\073\050\074\047\075\044\001\002\000\014\050\206\067" +
    "\207\073\050\074\047\075\044\001\002\000\010\051\uffec" +
    "\065\uffec\066\uffec\001\002\000\014\050\206\067\207\073" +
    "\050\074\047\075\044\001\002\000\014\050\206\067\207" +
    "\073\050\074\047\075\044\001\002\000\010\051\uffed\065" +
    "\211\066\uffed\001\002\000\010\051\uffee\065\uffee\066\uffee" +
    "\001\002\000\024\051\064\052\057\053\060\057\221\060" +
    "\224\061\220\062\223\063\225\064\222\001\002\000\010" +
    "\051\217\065\211\066\212\001\002\000\010\051\uffeb\065" +
    "\uffeb\066\uffeb\001\002\000\012\050\046\073\050\074\047" +
    "\075\044\001\002\000\012\050\046\073\050\074\047\075" +
    "\044\001\002\000\012\050\046\073\050\074\047\075\044" +
    "\001\002\000\012\050\046\073\050\074\047\075\044\001" +
    "\002\000\012\050\046\073\050\074\047\075\044\001\002" +
    "\000\012\050\046\073\050\074\047\075\044\001\002\000" +
    "\014\051\ufff0\052\057\053\060\065\ufff0\066\ufff0\001\002" +
    "\000\014\051\ufff3\052\057\053\060\065\ufff3\066\ufff3\001" +
    "\002\000\014\051\ufff1\052\057\053\060\065\ufff1\066\ufff1" +
    "\001\002\000\014\051\uffef\052\057\053\060\065\uffef\066" +
    "\uffef\001\002\000\014\051\ufff4\052\057\053\060\065\ufff4" +
    "\066\ufff4\001\002\000\014\051\ufff2\052\057\053\060\065" +
    "\ufff2\066\ufff2\001\002\000\004\011\235\001\002\000\016" +
    "\006\176\010\202\012\200\013\175\014\173\075\174\001" +
    "\002\000\020\005\237\006\176\010\202\012\200\013\175" +
    "\014\173\075\174\001\002\000\004\010\241\001\002\000" +
    "\020\005\ufffd\006\ufffd\010\ufffd\012\ufffd\013\ufffd\014\ufffd" +
    "\075\ufffd\001\002\000\020\005\ufff5\006\ufff5\010\ufff5\012" +
    "\ufff5\013\ufff5\014\ufff5\075\ufff5\001\002\000\020\005\ufff8" +
    "\006\ufff8\010\ufff8\012\ufff8\013\ufff8\014\ufff8\075\ufff8\001" +
    "\002\000\020\005\ufff9\006\ufff9\010\ufff9\012\ufff9\013\ufff9" +
    "\014\ufff9\075\ufff9\001\002\000\006\002\ufffe\015\ufffe\001" +
    "\002\000\014\050\206\067\207\073\050\074\047\075\044" +
    "\001\002\000\010\051\247\065\211\066\212\001\002\000" +
    "\004\007\250\001\002\000\016\006\176\010\202\012\200" +
    "\013\175\014\173\075\174\001\002\000\020\005\252\006" +
    "\176\010\202\012\200\013\175\014\173\075\174\001\002" +
    "\000\004\006\253\001\002\000\020\005\ufff6\006\ufff6\010" +
    "\ufff6\012\ufff6\013\ufff6\014\ufff6\075\ufff6\001\002\000\020" +
    "\005\ufff7\006\ufff7\010\ufff7\012\ufff7\013\ufff7\014\ufff7\075" +
    "\ufff7\001\002\000\012\050\046\073\050\074\047\075\044" +
    "\001\002\000\024\005\ufffa\006\ufffa\010\ufffa\012\ufffa\013" +
    "\ufffa\014\ufffa\052\057\053\060\075\ufffa\001\002\000\004" +
    "\056\260\001\002\000\012\050\046\073\050\074\047\075" +
    "\044\001\002\000\024\005\ufffb\006\ufffb\010\ufffb\012\ufffb" +
    "\013\ufffb\014\ufffb\052\057\053\060\075\ufffb\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\260\000\006\002\003\003\005\001\001\000\002\001" +
    "\001\000\006\004\176\005\200\001\001\000\002\001\001" +
    "\000\010\012\020\013\013\014\030\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\151\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\017" +
    "\034\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\007\050\010\051\011\044" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\007" +
    "\062\010\051\011\044\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\055\001\001\000\004\011\054\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\010\061\011\044\001\001\000" +
    "\006\010\060\011\044\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\007" +
    "\065\010\051\011\044\001\001\000\002\001\001\000\014" +
    "\007\071\010\051\011\044\015\070\016\072\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\007\074\010\051\011\044\001\001\000" +
    "\002\001\001\000\010\007\076\010\051\011\044\001\001" +
    "\000\002\001\001\000\010\007\100\010\051\011\044\001" +
    "\001\000\002\001\001\000\004\017\102\001\001\000\002" +
    "\001\001\000\010\007\104\010\051\011\044\001\001\000" +
    "\002\001\001\000\014\007\071\010\051\011\044\015\106" +
    "\016\072\001\001\000\002\001\001\000\010\007\110\010" +
    "\051\011\044\001\001\000\002\001\001\000\004\020\112" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\007\120" +
    "\010\051\011\044\001\001\000\002\001\001\000\014\007" +
    "\071\010\051\011\044\015\122\016\072\001\001\000\002" +
    "\001\001\000\010\007\124\010\051\011\044\001\001\000" +
    "\002\001\001\000\010\007\126\010\051\011\044\001\001" +
    "\000\002\001\001\000\010\007\130\010\051\011\044\001" +
    "\001\000\002\001\001\000\004\017\132\001\001\000\002" +
    "\001\001\000\010\007\134\010\051\011\044\001\001\000" +
    "\002\001\001\000\014\007\071\010\051\011\044\015\136" +
    "\016\072\001\001\000\002\001\001\000\010\007\140\010" +
    "\051\011\044\001\001\000\002\001\001\000\014\007\071" +
    "\010\051\011\044\015\142\016\072\001\001\000\002\001" +
    "\001\000\010\007\144\010\051\011\044\001\001\000\002" +
    "\001\001\000\010\007\146\010\051\011\044\001\001\000" +
    "\002\001\001\000\010\007\150\010\051\011\044\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\020\153\001" +
    "\001\000\002\001\001\000\010\007\155\010\051\011\044" +
    "\001\001\000\002\001\001\000\004\020\157\001\001\000" +
    "\002\001\001\000\010\007\161\010\051\011\044\001\001" +
    "\000\002\001\001\000\014\007\071\010\051\011\044\015" +
    "\163\016\072\001\001\000\002\001\001\000\010\007\165" +
    "\010\051\011\044\001\001\000\002\001\001\000\010\007" +
    "\167\010\051\011\044\001\001\000\002\001\001\000\010" +
    "\007\171\010\051\011\044\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\237\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\006\204\007\203" +
    "\010\051\011\044\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\006\215\007\214\010\051\011\044\001\001" +
    "\000\012\006\207\007\203\010\051\011\044\001\001\000" +
    "\002\001\001\000\012\006\213\007\203\010\051\011\044" +
    "\001\001\000\012\006\212\007\203\010\051\011\044\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\007\232\010" +
    "\051\011\044\001\001\000\010\007\231\010\051\011\044" +
    "\001\001\000\010\007\230\010\051\011\044\001\001\000" +
    "\010\007\227\010\051\011\044\001\001\000\010\007\226" +
    "\010\051\011\044\001\001\000\010\007\225\010\051\011" +
    "\044\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\004\235\005\200\001\001" +
    "\000\004\005\237\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\006\245\007\203\010\051\011" +
    "\044\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\004\250\005\200\001\001\000\004\005\237\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\007\255\010\051\011\044\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\007\260\010\051\011\044\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    Stack            stack,
    int                        top)
    throws Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    Lexer lexer;
    private List<String> erroresSintacticos;

    /* Falta recuperacion de errores*/

    public Parser(Lexer lexer) {
        super(lexer);
        this.lexer = lexer;
        erroresSintacticos = new ArrayList<>();
    }

    public Lexer getLexer(){
        return this.lexer;
    }
    
    public List<String> getSintaxError(){
        return erroresSintacticos; 
    }

 @Override
    public void syntax_error(Symbol cur_token){
        StringBuilder mssBuilder = new StringBuilder();
        mssBuilder.append(symbl_name_from_id(cur_token.sym));
        
        if(cur_token.value != null) {
            mssBuilder.append(cur_token.value.toString());
        }

        mssBuilder.append(", line: ");
        mssBuilder.append(cur_token.left);
        mssBuilder.append(", col: ");
        mssBuilder.append(cur_token.right);
        
        if( expected_token_ids().isEmpty()  ){
            mssBuilder.append(" -- ya no se esperaba ningun simbolo");
        } else {
            mssBuilder.append("Se esperaba: ");
            for(Integer expected_token_id : expected_token_ids() ){ 
                if(!symbl_name_from_id(expected_token_id).equals("error")){
                    mssBuilder.append(symbl_name_from_id(expected_token_id));
                    mssBuilder.append(" ");
                }
            }
        }
    }

 @Override
    public void unrecovered_syntax_error(Symbol cur_token){
        erroresSintacticos.add("Error que no se puede recuperar");
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= bloque_codigo 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= bloque_codigo SEPARADOR bloque_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // bloque_codigo ::= INICIO lista_sentencias FIN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_codigo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= VAR ID IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= ID IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= MOSTRAR CADENA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= MOSTRAR ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= LEER ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= SI PARENTESIS_ABIERTO condicion PARENTESIS_CERRADO ENTONCES lista_sentencias FIN SI 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= MIENTRAS PARENTESIS_ABIERTO condicion PARENTESIS_CERRADO HACER lista_sentencias FIN MIENTRAS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // condicion ::= expresion IGUAL_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // condicion ::= expresion DIFERENTE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // condicion ::= expresion MENOR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // condicion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // condicion ::= expresion MENOR_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // condicion ::= expresion MAYOR_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // condicion ::= condicion AND condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // condicion ::= condicion OR condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // condicion ::= NOT condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // condicion ::= PARENTESIS_ABIERTO condicion PARENTESIS_CERRADO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expresion ::= expresion MAS termino 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresion ::= expresion MENOS termino 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion ::= termino 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // termino ::= termino MULTIPLICADO factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // termino ::= termino DIVIDIDO factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // termino ::= factor 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // factor ::= ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // factor ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // factor ::= ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // factor ::= PARENTESIS_ABIERTO expresion PARENTESIS_CERRADO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // bloque_config ::= lista_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_config",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_config ::= lista_config instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_config",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // lista_config ::= instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_config",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // instruccion_config ::= DEFAULT IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // instruccion_config ::= COLOR_TEXTO_SI IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // instruccion_config ::= COLOR_SI IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // instruccion_config ::= FIGURA_SI IGUAL figura PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // instruccion_config ::= LETRA_SI IGUAL letra PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // instruccion_config ::= LETRA_SIZE_SI IGUAL expresion PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // instruccion_config ::= COLOR_TEXTO_MIENTRAS IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // instruccion_config ::= COLOR_MIENTRAS IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // instruccion_config ::= FIGURA_MIENTRAS IGUAL figura PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // instruccion_config ::= LETRA_MIENTRAS IGUAL letra PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // instruccion_config ::= LETRA_SIZE_MIENTRAS IGUAL expresion PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // instruccion_config ::= COLOR_TEXTO_BLOQUE IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // instruccion_config ::= COLOR_BLOQUE IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // instruccion_config ::= FIGURA_BLOQUE IGUAL figura PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // instruccion_config ::= LETRA_BLOQUE IGUAL letra PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // instruccion_config ::= LETRA_SIZE_BLOQUE IGUAL expresion PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // color ::= COLOR_HEX 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("color",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // color ::= rgb 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("color",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // rgb ::= expresion COMA expresion COMA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("rgb",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // figura ::= ELIPSE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // figura ::= CIRCULO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // figura ::= PARALELOGRAMO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // figura ::= RECTANGULO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // figura ::= ROMBO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // figura ::= RECTANGULO_REDONDEADO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // letra ::= ARIAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // letra ::= TIMES_NEW_ROMAN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // letra ::= COMIC_SANS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // letra ::= VERDANA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
