
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.aplicacioncompi1.uitheme.logic;

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\111\000\002\002\004\000\002\002\003\000\002\002" +
    "\005\000\002\002\005\000\002\003\005\000\002\003\005" +
    "\000\002\004\004\000\002\004\003\000\002\004\005\000" +
    "\002\004\004\000\002\005\006\000\002\005\005\000\002" +
    "\005\004\000\002\005\004\000\002\005\004\000\002\005" +
    "\012\000\002\005\010\000\002\005\012\000\002\005\010" +
    "\000\002\006\005\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\006\005\000\002\006\005\000\002" +
    "\006\005\000\002\006\005\000\002\006\004\000\002\006" +
    "\005\000\002\007\005\000\002\007\005\000\002\007\003" +
    "\000\002\010\005\000\002\010\005\000\002\010\003\000" +
    "\002\011\003\000\002\011\003\000\002\011\003\000\002" +
    "\011\005\000\002\012\003\000\002\013\004\000\002\013" +
    "\003\000\002\013\005\000\002\013\004\000\002\014\005" +
    "\000\002\014\007\000\002\014\007\000\002\014\007\000" +
    "\002\014\007\000\002\014\007\000\002\014\007\000\002" +
    "\014\007\000\002\014\007\000\002\014\007\000\002\014" +
    "\007\000\002\014\007\000\002\014\007\000\002\014\007" +
    "\000\002\014\007\000\002\014\007\000\002\015\003\000" +
    "\002\015\003\000\002\016\007\000\002\017\003\000\002" +
    "\017\003\000\002\017\003\000\002\017\003\000\002\017" +
    "\003\000\002\017\003\000\002\020\003\000\002\020\003" +
    "\000\002\020\003\000\002\020\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\307\000\006\003\005\004\006\001\002\000\004\002" +
    "\311\001\002\000\004\015\307\001\002\000\020\003\205" +
    "\006\210\010\206\012\201\013\203\014\202\075\204\001" +
    "\002\000\006\002\000\015\010\001\002\000\044\003\030" +
    "\016\032\017\024\020\031\021\021\022\013\023\011\024" +
    "\026\025\020\026\027\027\025\030\015\031\012\032\017" +
    "\033\034\034\014\035\022\001\002\000\004\056\174\001" +
    "\002\000\004\056\170\001\002\000\004\056\164\001\002" +
    "\000\004\056\160\001\002\000\004\056\154\001\002\000" +
    "\046\002\uffda\003\151\016\032\017\024\020\031\021\021" +
    "\022\013\023\011\024\026\025\020\026\027\027\025\030" +
    "\015\031\012\032\017\033\034\034\014\035\022\001\002" +
    "\000\004\056\145\001\002\000\004\056\141\001\002\000" +
    "\004\056\135\001\002\000\004\056\131\001\002\000\004" +
    "\002\uffff\001\002\000\004\056\125\001\002\000\004\056" +
    "\115\001\002\000\004\056\111\001\002\000\004\056\105" +
    "\001\002\000\042\016\032\017\024\020\031\021\021\022" +
    "\013\023\011\024\026\025\020\026\027\027\025\030\015" +
    "\031\012\032\017\033\034\034\014\035\022\001\002\000" +
    "\004\056\071\001\002\000\004\056\067\001\002\000\046" +
    "\002\uffd8\003\uffd8\016\uffd8\017\uffd8\020\uffd8\021\uffd8\022" +
    "\uffd8\023\uffd8\024\uffd8\025\uffd8\026\uffd8\027\uffd8\030\uffd8" +
    "\031\uffd8\032\uffd8\033\uffd8\034\uffd8\035\uffd8\001\002\000" +
    "\004\056\035\001\002\000\016\036\044\037\042\040\041" +
    "\041\036\042\043\043\040\001\002\000\004\071\uffbf\001" +
    "\002\000\004\071\045\001\002\000\004\071\uffbd\001\002" +
    "\000\004\071\uffc0\001\002\000\004\071\uffc1\001\002\000" +
    "\004\071\uffbe\001\002\000\004\071\uffc2\001\002\000\012" +
    "\050\050\073\052\074\051\075\046\001\002\000\122\002" +
    "\uffdc\003\uffdc\005\uffdc\006\uffdc\010\uffdc\012\uffdc\013\uffdc" +
    "\014\uffdc\016\uffdc\017\uffdc\020\uffdc\021\uffdc\022\uffdc\023" +
    "\uffdc\024\uffdc\025\uffdc\026\uffdc\027\uffdc\030\uffdc\031\uffdc" +
    "\032\uffdc\033\uffdc\034\uffdc\035\uffdc\051\uffdc\052\uffdc\053" +
    "\uffdc\054\uffdc\055\uffdc\057\uffdc\060\uffdc\061\uffdc\062\uffdc" +
    "\063\uffdc\064\uffdc\065\uffdc\066\uffdc\070\uffdc\071\uffdc\075" +
    "\uffdc\001\002\000\122\002\uffdf\003\uffdf\005\uffdf\006\uffdf" +
    "\010\uffdf\012\uffdf\013\uffdf\014\uffdf\016\uffdf\017\uffdf\020" +
    "\uffdf\021\uffdf\022\uffdf\023\uffdf\024\uffdf\025\uffdf\026\uffdf" +
    "\027\uffdf\030\uffdf\031\uffdf\032\uffdf\033\uffdf\034\uffdf\035" +
    "\uffdf\051\uffdf\052\uffdf\053\uffdf\054\uffdf\055\uffdf\057\uffdf" +
    "\060\uffdf\061\uffdf\062\uffdf\063\uffdf\064\uffdf\065\uffdf\066" +
    "\uffdf\070\uffdf\071\uffdf\075\uffdf\001\002\000\012\050\050" +
    "\073\052\074\051\075\046\001\002\000\122\002\uffdd\003" +
    "\uffdd\005\uffdd\006\uffdd\010\uffdd\012\uffdd\013\uffdd\014\uffdd" +
    "\016\uffdd\017\uffdd\020\uffdd\021\uffdd\022\uffdd\023\uffdd\024" +
    "\uffdd\025\uffdd\026\uffdd\027\uffdd\030\uffdd\031\uffdd\032\uffdd" +
    "\033\uffdd\034\uffdd\035\uffdd\051\uffdd\052\uffdd\053\uffdd\054" +
    "\uffdd\055\uffdd\057\uffdd\060\uffdd\061\uffdd\062\uffdd\063\uffdd" +
    "\064\uffdd\065\uffdd\066\uffdd\070\uffdd\071\uffdd\075\uffdd\001" +
    "\002\000\122\002\uffde\003\uffde\005\uffde\006\uffde\010\uffde" +
    "\012\uffde\013\uffde\014\uffde\016\uffde\017\uffde\020\uffde\021" +
    "\uffde\022\uffde\023\uffde\024\uffde\025\uffde\026\uffde\027\uffde" +
    "\030\uffde\031\uffde\032\uffde\033\uffde\034\uffde\035\uffde\051" +
    "\uffde\052\uffde\053\uffde\054\uffde\055\uffde\057\uffde\060\uffde" +
    "\061\uffde\062\uffde\063\uffde\064\uffde\065\uffde\066\uffde\070" +
    "\uffde\071\uffde\075\uffde\001\002\000\052\002\uffc8\003\uffc8" +
    "\016\uffc8\017\uffc8\020\uffc8\021\uffc8\022\uffc8\023\uffc8\024" +
    "\uffc8\025\uffc8\026\uffc8\027\uffc8\030\uffc8\031\uffc8\032\uffc8" +
    "\033\uffc8\034\uffc8\035\uffc8\052\061\053\062\001\002\000" +
    "\122\002\uffe2\003\uffe2\005\uffe2\006\uffe2\010\uffe2\012\uffe2" +
    "\013\uffe2\014\uffe2\016\uffe2\017\uffe2\020\uffe2\021\uffe2\022" +
    "\uffe2\023\uffe2\024\uffe2\025\uffe2\026\uffe2\027\uffe2\030\uffe2" +
    "\031\uffe2\032\uffe2\033\uffe2\034\uffe2\035\uffe2\051\uffe2\052" +
    "\uffe2\053\uffe2\054\055\055\056\057\uffe2\060\uffe2\061\uffe2" +
    "\062\uffe2\063\uffe2\064\uffe2\065\uffe2\066\uffe2\070\uffe2\071" +
    "\uffe2\075\uffe2\001\002\000\012\050\050\073\052\074\051" +
    "\075\046\001\002\000\012\050\050\073\052\074\051\075" +
    "\046\001\002\000\122\002\uffe0\003\uffe0\005\uffe0\006\uffe0" +
    "\010\uffe0\012\uffe0\013\uffe0\014\uffe0\016\uffe0\017\uffe0\020" +
    "\uffe0\021\uffe0\022\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0" +
    "\027\uffe0\030\uffe0\031\uffe0\032\uffe0\033\uffe0\034\uffe0\035" +
    "\uffe0\051\uffe0\052\uffe0\053\uffe0\054\uffe0\055\uffe0\057\uffe0" +
    "\060\uffe0\061\uffe0\062\uffe0\063\uffe0\064\uffe0\065\uffe0\066" +
    "\uffe0\070\uffe0\071\uffe0\075\uffe0\001\002\000\122\002\uffe1" +
    "\003\uffe1\005\uffe1\006\uffe1\010\uffe1\012\uffe1\013\uffe1\014" +
    "\uffe1\016\uffe1\017\uffe1\020\uffe1\021\uffe1\022\uffe1\023\uffe1" +
    "\024\uffe1\025\uffe1\026\uffe1\027\uffe1\030\uffe1\031\uffe1\032" +
    "\uffe1\033\uffe1\034\uffe1\035\uffe1\051\uffe1\052\uffe1\053\uffe1" +
    "\054\uffe1\055\uffe1\057\uffe1\060\uffe1\061\uffe1\062\uffe1\063" +
    "\uffe1\064\uffe1\065\uffe1\066\uffe1\070\uffe1\071\uffe1\075\uffe1" +
    "\001\002\000\012\050\050\073\052\074\051\075\046\001" +
    "\002\000\012\050\050\073\052\074\051\075\046\001\002" +
    "\000\122\002\uffe3\003\uffe3\005\uffe3\006\uffe3\010\uffe3\012" +
    "\uffe3\013\uffe3\014\uffe3\016\uffe3\017\uffe3\020\uffe3\021\uffe3" +
    "\022\uffe3\023\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3\030" +
    "\uffe3\031\uffe3\032\uffe3\033\uffe3\034\uffe3\035\uffe3\051\uffe3" +
    "\052\uffe3\053\uffe3\054\055\055\056\057\uffe3\060\uffe3\061" +
    "\uffe3\062\uffe3\063\uffe3\064\uffe3\065\uffe3\066\uffe3\070\uffe3" +
    "\071\uffe3\075\uffe3\001\002\000\122\002\uffe4\003\uffe4\005" +
    "\uffe4\006\uffe4\010\uffe4\012\uffe4\013\uffe4\014\uffe4\016\uffe4" +
    "\017\uffe4\020\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025" +
    "\uffe4\026\uffe4\027\uffe4\030\uffe4\031\uffe4\032\uffe4\033\uffe4" +
    "\034\uffe4\035\uffe4\051\uffe4\052\uffe4\053\uffe4\054\055\055" +
    "\056\057\uffe4\060\uffe4\061\uffe4\062\uffe4\063\uffe4\064\uffe4" +
    "\065\uffe4\066\uffe4\070\uffe4\071\uffe4\075\uffe4\001\002\000" +
    "\010\051\066\052\061\053\062\001\002\000\122\002\uffdb" +
    "\003\uffdb\005\uffdb\006\uffdb\010\uffdb\012\uffdb\013\uffdb\014" +
    "\uffdb\016\uffdb\017\uffdb\020\uffdb\021\uffdb\022\uffdb\023\uffdb" +
    "\024\uffdb\025\uffdb\026\uffdb\027\uffdb\030\uffdb\031\uffdb\032" +
    "\uffdb\033\uffdb\034\uffdb\035\uffdb\051\uffdb\052\uffdb\053\uffdb" +
    "\054\uffdb\055\uffdb\057\uffdb\060\uffdb\061\uffdb\062\uffdb\063" +
    "\uffdb\064\uffdb\065\uffdb\066\uffdb\070\uffdb\071\uffdb\075\uffdb" +
    "\001\002\000\012\050\050\073\052\074\051\075\046\001" +
    "\002\000\052\002\uffd5\003\uffd5\016\uffd5\017\uffd5\020\uffd5" +
    "\021\uffd5\022\uffd5\023\uffd5\024\uffd5\025\uffd5\026\uffd5\027" +
    "\uffd5\030\uffd5\031\uffd5\032\uffd5\033\uffd5\034\uffd5\035\uffd5" +
    "\052\061\053\062\001\002\000\014\050\050\073\052\074" +
    "\051\075\046\076\072\001\002\000\004\071\uffc5\001\002" +
    "\000\004\071\102\001\002\000\010\052\061\053\062\070" +
    "\076\001\002\000\004\071\uffc4\001\002\000\012\050\050" +
    "\073\052\074\051\075\046\001\002\000\010\052\061\053" +
    "\062\070\100\001\002\000\012\050\050\073\052\074\051" +
    "\075\046\001\002\000\010\052\061\053\062\071\uffc3\001" +
    "\002\000\012\050\050\073\052\074\051\075\046\001\002" +
    "\000\052\002\uffd3\003\uffd3\016\uffd3\017\uffd3\020\uffd3\021" +
    "\uffd3\022\uffd3\023\uffd3\024\uffd3\025\uffd3\026\uffd3\027\uffd3" +
    "\030\uffd3\031\uffd3\032\uffd3\033\uffd3\034\uffd3\035\uffd3\052" +
    "\061\053\062\001\002\000\046\002\uffd6\003\uffd6\016\uffd6" +
    "\017\uffd6\020\uffd6\021\uffd6\022\uffd6\023\uffd6\024\uffd6\025" +
    "\uffd6\026\uffd6\027\uffd6\030\uffd6\031\uffd6\032\uffd6\033\uffd6" +
    "\034\uffd6\035\uffd6\001\002\000\016\036\044\037\042\040" +
    "\041\041\036\042\043\043\040\001\002\000\004\071\107" +
    "\001\002\000\012\050\050\073\052\074\051\075\046\001" +
    "\002\000\052\002\uffcd\003\uffcd\016\uffcd\017\uffcd\020\uffcd" +
    "\021\uffcd\022\uffcd\023\uffcd\024\uffcd\025\uffcd\026\uffcd\027" +
    "\uffcd\030\uffcd\031\uffcd\032\uffcd\033\uffcd\034\uffcd\035\uffcd" +
    "\052\061\053\062\001\002\000\014\050\050\073\052\074" +
    "\051\075\046\076\072\001\002\000\004\071\113\001\002" +
    "\000\012\050\050\073\052\074\051\075\046\001\002\000" +
    "\052\002\uffcf\003\uffcf\016\uffcf\017\uffcf\020\uffcf\021\uffcf" +
    "\022\uffcf\023\uffcf\024\uffcf\025\uffcf\026\uffcf\027\uffcf\030" +
    "\uffcf\031\uffcf\032\uffcf\033\uffcf\034\uffcf\035\uffcf\052\061" +
    "\053\062\001\002\000\012\044\120\045\122\046\117\047" +
    "\121\001\002\000\004\071\123\001\002\000\004\071\uffba" +
    "\001\002\000\004\071\uffbc\001\002\000\004\071\uffb9\001" +
    "\002\000\004\071\uffbb\001\002\000\012\050\050\073\052" +
    "\074\051\075\046\001\002\000\052\002\uffcc\003\uffcc\016" +
    "\uffcc\017\uffcc\020\uffcc\021\uffcc\022\uffcc\023\uffcc\024\uffcc" +
    "\025\uffcc\026\uffcc\027\uffcc\030\uffcc\031\uffcc\032\uffcc\033" +
    "\uffcc\034\uffcc\035\uffcc\052\061\053\062\001\002\000\014" +
    "\050\050\073\052\074\051\075\046\076\072\001\002\000" +
    "\004\071\127\001\002\000\012\050\050\073\052\074\051" +
    "\075\046\001\002\000\052\002\uffd4\003\uffd4\016\uffd4\017" +
    "\uffd4\020\uffd4\021\uffd4\022\uffd4\023\uffd4\024\uffd4\025\uffd4" +
    "\026\uffd4\027\uffd4\030\uffd4\031\uffd4\032\uffd4\033\uffd4\034" +
    "\uffd4\035\uffd4\052\061\053\062\001\002\000\012\050\050" +
    "\073\052\074\051\075\046\001\002\000\010\052\061\053" +
    "\062\071\133\001\002\000\012\050\050\073\052\074\051" +
    "\075\046\001\002\000\052\002\uffc6\003\uffc6\016\uffc6\017" +
    "\uffc6\020\uffc6\021\uffc6\022\uffc6\023\uffc6\024\uffc6\025\uffc6" +
    "\026\uffc6\027\uffc6\030\uffc6\031\uffc6\032\uffc6\033\uffc6\034" +
    "\uffc6\035\uffc6\052\061\053\062\001\002\000\016\036\044" +
    "\037\042\040\041\041\036\042\043\043\040\001\002\000" +
    "\004\071\137\001\002\000\012\050\050\073\052\074\051" +
    "\075\046\001\002\000\052\002\uffd2\003\uffd2\016\uffd2\017" +
    "\uffd2\020\uffd2\021\uffd2\022\uffd2\023\uffd2\024\uffd2\025\uffd2" +
    "\026\uffd2\027\uffd2\030\uffd2\031\uffd2\032\uffd2\033\uffd2\034" +
    "\uffd2\035\uffd2\052\061\053\062\001\002\000\014\050\050" +
    "\073\052\074\051\075\046\076\072\001\002\000\004\071" +
    "\143\001\002\000\012\050\050\073\052\074\051\075\046" +
    "\001\002\000\052\002\uffce\003\uffce\016\uffce\017\uffce\020" +
    "\uffce\021\uffce\022\uffce\023\uffce\024\uffce\025\uffce\026\uffce" +
    "\027\uffce\030\uffce\031\uffce\032\uffce\033\uffce\034\uffce\035" +
    "\uffce\052\061\053\062\001\002\000\014\050\050\073\052" +
    "\074\051\075\046\076\072\001\002\000\004\071\147\001" +
    "\002\000\012\050\050\073\052\074\051\075\046\001\002" +
    "\000\052\002\uffc9\003\uffc9\016\uffc9\017\uffc9\020\uffc9\021" +
    "\uffc9\022\uffc9\023\uffc9\024\uffc9\025\uffc9\026\uffc9\027\uffc9" +
    "\030\uffc9\031\uffc9\032\uffc9\033\uffc9\034\uffc9\035\uffc9\052" +
    "\061\053\062\001\002\000\042\016\032\017\024\020\031" +
    "\021\021\022\013\023\011\024\026\025\020\026\027\027" +
    "\025\030\015\031\012\032\017\033\034\034\014\035\022" +
    "\001\002\000\046\002\uffd9\003\uffd9\016\uffd9\017\uffd9\020" +
    "\uffd9\021\uffd9\022\uffd9\023\uffd9\024\uffd9\025\uffd9\026\uffd9" +
    "\027\uffd9\030\uffd9\031\uffd9\032\uffd9\033\uffd9\034\uffd9\035" +
    "\uffd9\001\002\000\046\002\uffd7\003\uffd7\016\uffd7\017\uffd7" +
    "\020\uffd7\021\uffd7\022\uffd7\023\uffd7\024\uffd7\025\uffd7\026" +
    "\uffd7\027\uffd7\030\uffd7\031\uffd7\032\uffd7\033\uffd7\034\uffd7" +
    "\035\uffd7\001\002\000\012\050\050\073\052\074\051\075" +
    "\046\001\002\000\010\052\061\053\062\071\156\001\002" +
    "\000\012\050\050\073\052\074\051\075\046\001\002\000" +
    "\052\002\uffcb\003\uffcb\016\uffcb\017\uffcb\020\uffcb\021\uffcb" +
    "\022\uffcb\023\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb\030" +
    "\uffcb\031\uffcb\032\uffcb\033\uffcb\034\uffcb\035\uffcb\052\061" +
    "\053\062\001\002\000\012\044\120\045\122\046\117\047" +
    "\121\001\002\000\004\071\162\001\002\000\012\050\050" +
    "\073\052\074\051\075\046\001\002\000\052\002\uffc7\003" +
    "\uffc7\016\uffc7\017\uffc7\020\uffc7\021\uffc7\022\uffc7\023\uffc7" +
    "\024\uffc7\025\uffc7\026\uffc7\027\uffc7\030\uffc7\031\uffc7\032" +
    "\uffc7\033\uffc7\034\uffc7\035\uffc7\052\061\053\062\001\002" +
    "\000\012\044\120\045\122\046\117\047\121\001\002\000" +
    "\004\071\166\001\002\000\012\050\050\073\052\074\051" +
    "\075\046\001\002\000\052\002\uffd1\003\uffd1\016\uffd1\017" +
    "\uffd1\020\uffd1\021\uffd1\022\uffd1\023\uffd1\024\uffd1\025\uffd1" +
    "\026\uffd1\027\uffd1\030\uffd1\031\uffd1\032\uffd1\033\uffd1\034" +
    "\uffd1\035\uffd1\052\061\053\062\001\002\000\014\050\050" +
    "\073\052\074\051\075\046\076\072\001\002\000\004\071" +
    "\172\001\002\000\012\050\050\073\052\074\051\075\046" +
    "\001\002\000\052\002\uffca\003\uffca\016\uffca\017\uffca\020" +
    "\uffca\021\uffca\022\uffca\023\uffca\024\uffca\025\uffca\026\uffca" +
    "\027\uffca\030\uffca\031\uffca\032\uffca\033\uffca\034\uffca\035" +
    "\uffca\052\061\053\062\001\002\000\012\050\050\073\052" +
    "\074\051\075\046\001\002\000\010\052\061\053\062\071" +
    "\176\001\002\000\012\050\050\073\052\074\051\075\046" +
    "\001\002\000\052\002\uffd0\003\uffd0\016\uffd0\017\uffd0\020" +
    "\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0\026\uffd0" +
    "\027\uffd0\030\uffd0\031\uffd0\032\uffd0\033\uffd0\034\uffd0\035" +
    "\uffd0\052\061\053\062\001\002\000\022\003\ufffa\005\ufffa" +
    "\006\ufffa\010\ufffa\012\ufffa\013\ufffa\014\ufffa\075\ufffa\001" +
    "\002\000\006\072\306\075\305\001\002\000\004\075\302" +
    "\001\002\000\004\075\301\001\002\000\004\056\277\001" +
    "\002\000\020\005\276\006\210\010\206\012\201\013\203" +
    "\014\202\075\204\001\002\000\006\003\262\050\263\001" +
    "\002\000\022\003\251\005\261\006\210\010\206\012\201" +
    "\013\203\014\202\075\204\001\002\000\006\003\211\050" +
    "\212\001\002\000\004\007\255\001\002\000\014\050\215" +
    "\067\216\073\052\074\051\075\046\001\002\000\022\052" +
    "\061\053\062\057\230\060\233\061\227\062\232\063\234" +
    "\064\231\001\002\000\010\051\243\065\220\066\221\001" +
    "\002\000\014\050\215\067\216\073\052\074\051\075\046" +
    "\001\002\000\014\050\215\067\216\073\052\074\051\075" +
    "\046\001\002\000\010\051\uffe6\065\uffe6\066\uffe6\001\002" +
    "\000\014\050\215\067\216\073\052\074\051\075\046\001" +
    "\002\000\014\050\215\067\216\073\052\074\051\075\046" +
    "\001\002\000\010\051\uffe7\065\220\066\uffe7\001\002\000" +
    "\010\051\uffe8\065\uffe8\066\uffe8\001\002\000\024\051\066" +
    "\052\061\053\062\057\230\060\233\061\227\062\232\063" +
    "\234\064\231\001\002\000\010\051\226\065\220\066\221" +
    "\001\002\000\010\051\uffe5\065\uffe5\066\uffe5\001\002\000" +
    "\012\050\050\073\052\074\051\075\046\001\002\000\012" +
    "\050\050\073\052\074\051\075\046\001\002\000\012\050" +
    "\050\073\052\074\051\075\046\001\002\000\012\050\050" +
    "\073\052\074\051\075\046\001\002\000\012\050\050\073" +
    "\052\074\051\075\046\001\002\000\012\050\050\073\052" +
    "\074\051\075\046\001\002\000\014\051\uffea\052\061\053" +
    "\062\065\uffea\066\uffea\001\002\000\014\051\uffed\052\061" +
    "\053\062\065\uffed\066\uffed\001\002\000\014\051\uffeb\052" +
    "\061\053\062\065\uffeb\066\uffeb\001\002\000\014\051\uffe9" +
    "\052\061\053\062\065\uffe9\066\uffe9\001\002\000\014\051" +
    "\uffee\052\061\053\062\065\uffee\066\uffee\001\002\000\014" +
    "\051\uffec\052\061\053\062\065\uffec\066\uffec\001\002\000" +
    "\004\007\244\001\002\000\020\003\245\006\210\010\206" +
    "\012\201\013\203\014\202\075\204\001\002\000\016\006" +
    "\210\010\206\012\201\013\203\014\202\075\204\001\002" +
    "\000\022\003\251\005\250\006\210\010\206\012\201\013" +
    "\203\014\202\075\204\001\002\000\022\003\ufffb\005\ufffb" +
    "\006\ufffb\010\ufffb\012\ufffb\013\ufffb\014\ufffb\075\ufffb\001" +
    "\002\000\004\006\253\001\002\000\016\006\210\010\206" +
    "\012\201\013\203\014\202\075\204\001\002\000\022\003" +
    "\ufff9\005\ufff9\006\ufff9\010\ufff9\012\ufff9\013\ufff9\014\ufff9" +
    "\075\ufff9\001\002\000\022\003\ufff2\005\ufff2\006\ufff2\010" +
    "\ufff2\012\ufff2\013\ufff2\014\ufff2\075\ufff2\001\002\000\022" +
    "\003\ufff8\005\ufff8\006\ufff8\010\ufff8\012\ufff8\013\ufff8\014" +
    "\ufff8\075\ufff8\001\002\000\020\003\245\006\210\010\206" +
    "\012\201\013\203\014\202\075\204\001\002\000\022\003" +
    "\251\005\257\006\210\010\206\012\201\013\203\014\202" +
    "\075\204\001\002\000\004\006\260\001\002\000\022\003" +
    "\ufff1\005\ufff1\006\ufff1\010\ufff1\012\ufff1\013\ufff1\014\ufff1" +
    "\075\ufff1\001\002\000\006\002\ufffd\015\ufffd\001\002\000" +
    "\004\011\272\001\002\000\014\050\215\067\216\073\052" +
    "\074\051\075\046\001\002\000\010\051\265\065\220\066" +
    "\221\001\002\000\004\011\266\001\002\000\020\003\245" +
    "\006\210\010\206\012\201\013\203\014\202\075\204\001" +
    "\002\000\022\003\251\005\270\006\210\010\206\012\201" +
    "\013\203\014\202\075\204\001\002\000\004\010\271\001" +
    "\002\000\022\003\ufff0\005\ufff0\006\ufff0\010\ufff0\012\ufff0" +
    "\013\ufff0\014\ufff0\075\ufff0\001\002\000\020\003\245\006" +
    "\210\010\206\012\201\013\203\014\202\075\204\001\002" +
    "\000\022\003\251\005\274\006\210\010\206\012\201\013" +
    "\203\014\202\075\204\001\002\000\004\010\275\001\002" +
    "\000\022\003\uffef\005\uffef\006\uffef\010\uffef\012\uffef\013" +
    "\uffef\014\uffef\075\uffef\001\002\000\006\002\ufffc\015\ufffc" +
    "\001\002\000\012\050\050\073\052\074\051\075\046\001" +
    "\002\000\026\003\ufff6\005\ufff6\006\ufff6\010\ufff6\012\ufff6" +
    "\013\ufff6\014\ufff6\052\061\053\062\075\ufff6\001\002\000" +
    "\022\003\ufff3\005\ufff3\006\ufff3\010\ufff3\012\ufff3\013\ufff3" +
    "\014\ufff3\075\ufff3\001\002\000\004\056\303\001\002\000" +
    "\012\050\050\073\052\074\051\075\046\001\002\000\026" +
    "\003\ufff7\005\ufff7\006\ufff7\010\ufff7\012\ufff7\013\ufff7\014" +
    "\ufff7\052\061\053\062\075\ufff7\001\002\000\022\003\ufff4" +
    "\005\ufff4\006\ufff4\010\ufff4\012\ufff4\013\ufff4\014\ufff4\075" +
    "\ufff4\001\002\000\022\003\ufff5\005\ufff5\006\ufff5\010\ufff5" +
    "\012\ufff5\013\ufff5\014\ufff5\075\ufff5\001\002\000\044\003" +
    "\030\016\032\017\024\020\031\021\021\022\013\023\011" +
    "\024\026\025\020\026\027\027\025\030\015\031\012\032" +
    "\017\033\034\034\014\035\022\001\002\000\004\002\ufffe" +
    "\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\307\000\006\002\003\003\006\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\004\206\005\177\001\001" +
    "\000\002\001\001\000\010\012\022\013\015\014\032\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\014\151\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\014\103\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\017\036\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\007\052\010\053\011\046\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\007\064\010\053" +
    "\011\046\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\057\001\001" +
    "\000\004\011\056\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\010\063\011\046\001\001\000\006\010\062" +
    "\011\046\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\007\067\010\053" +
    "\011\046\001\001\000\002\001\001\000\014\007\073\010" +
    "\053\011\046\015\072\016\074\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\007\076\010\053\011\046\001\001\000\002\001\001" +
    "\000\010\007\100\010\053\011\046\001\001\000\002\001" +
    "\001\000\010\007\102\010\053\011\046\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\017\105\001\001\000" +
    "\002\001\001\000\010\007\107\010\053\011\046\001\001" +
    "\000\002\001\001\000\014\007\073\010\053\011\046\015" +
    "\111\016\074\001\001\000\002\001\001\000\010\007\113" +
    "\010\053\011\046\001\001\000\002\001\001\000\004\020" +
    "\115\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\007" +
    "\123\010\053\011\046\001\001\000\002\001\001\000\014" +
    "\007\073\010\053\011\046\015\125\016\074\001\001\000" +
    "\002\001\001\000\010\007\127\010\053\011\046\001\001" +
    "\000\002\001\001\000\010\007\131\010\053\011\046\001" +
    "\001\000\002\001\001\000\010\007\133\010\053\011\046" +
    "\001\001\000\002\001\001\000\004\017\135\001\001\000" +
    "\002\001\001\000\010\007\137\010\053\011\046\001\001" +
    "\000\002\001\001\000\014\007\073\010\053\011\046\015" +
    "\141\016\074\001\001\000\002\001\001\000\010\007\143" +
    "\010\053\011\046\001\001\000\002\001\001\000\014\007" +
    "\073\010\053\011\046\015\145\016\074\001\001\000\002" +
    "\001\001\000\010\007\147\010\053\011\046\001\001\000" +
    "\002\001\001\000\004\014\152\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\007\154\010\053\011\046\001" +
    "\001\000\002\001\001\000\010\007\156\010\053\011\046" +
    "\001\001\000\002\001\001\000\004\020\160\001\001\000" +
    "\002\001\001\000\010\007\162\010\053\011\046\001\001" +
    "\000\002\001\001\000\004\020\164\001\001\000\002\001" +
    "\001\000\010\007\166\010\053\011\046\001\001\000\002" +
    "\001\001\000\014\007\073\010\053\011\046\015\170\016" +
    "\074\001\001\000\002\001\001\000\010\007\172\010\053" +
    "\011\046\001\001\000\002\001\001\000\010\007\174\010" +
    "\053\011\046\001\001\000\002\001\001\000\010\007\176" +
    "\010\053\011\046\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\253\001\001\000\002\001" +
    "\001\000\004\005\246\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\006\213\007\212\010\053\011\046\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\006\224" +
    "\007\223\010\053\011\046\001\001\000\012\006\216\007" +
    "\212\010\053\011\046\001\001\000\002\001\001\000\012" +
    "\006\222\007\212\010\053\011\046\001\001\000\012\006" +
    "\221\007\212\010\053\011\046\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\007\241\010\053\011\046\001\001" +
    "\000\010\007\240\010\053\011\046\001\001\000\010\007" +
    "\237\010\053\011\046\001\001\000\010\007\236\010\053" +
    "\011\046\001\001\000\010\007\235\010\053\011\046\001" +
    "\001\000\010\007\234\010\053\011\046\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\004\245\005\177\001\001\000\004\005\253\001" +
    "\001\000\004\005\246\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\251\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\004\255\005\177" +
    "\001\001\000\004\005\246\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\006\263\007\212\010\053\011\046\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\004\266\005\177\001\001" +
    "\000\004\005\246\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\004\272\005\177\001\001\000\004\005\246" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\007\277\010\053\011\046\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\007" +
    "\303\010\053\011\046\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\012\307\013\015\014" +
    "\032\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public Symbol do_action(
    int                        act_num,
    lr_parser parser,
    Stack            stack,
    int                        top)
    throws Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    Lexer lexer;
    private List<ErrorSintactico> erroresSintacticos;
    private List<ReporteOperador> operadores = new ArrayList<>();
    private List<ReporteControl> estructuras = new ArrayList<>();

    public List<ReporteOperador> getOperadores() { return operadores; }
    public List<ReporteControl> getEstructuras() { return estructuras; }

    public Parser(Lexer lexer) {
        super(lexer);
        this.lexer = lexer;
        erroresSintacticos = new ArrayList<>();
    }

    public Lexer getLexer(){
        return this.lexer;
    }
    
    public List<ErrorSintactico> getSintaxError(){
        return erroresSintacticos; 
    }

    @Override
    public void syntax_error(Symbol cur_token){
        String lexema = (cur_token.value != null) ? cur_token.value.toString() : symbl_name_from_id(cur_token.sym);
        
        int linea = cur_token.left;
        int columna = cur_token.right;
        
        StringBuilder descripcion = new StringBuilder();
        if( expected_token_ids().isEmpty()  ){
            descripcion.append("Ya no se esperaba ningun simbolo");
        } else {
            descripcion.append("Se esperaba: ");
            for(Integer expected_token_id : expected_token_ids() ){ 
                if(!symbl_name_from_id(expected_token_id).equals("error")){
                    descripcion.append(symbl_name_from_id(expected_token_id));
                    descripcion.append(" ");
                }
            }
        }
        
        erroresSintacticos.add(new ErrorSintactico(lexema, linea, columna, descripcion.toString())); 
    }

    @Override
    public void unrecovered_syntax_error(Symbol cur_token){
        String lexema = (cur_token.value != null) ? cur_token.value.toString() : symbl_name_from_id(cur_token.sym);
        erroresSintacticos.add(new ErrorSintactico(lexema, cur_token.left, cur_token.right, "Error sintáctico irrecuperable."));
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    lr_parser CUP$Parser$parser,
    Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws Exception
    {
      /* Symbol object for return from actions */
      Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= bloque_codigo 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= bloque_codigo SEPARADOR bloque_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= error SEPARADOR bloque_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // bloque_codigo ::= INICIO lista_sentencias FIN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_codigo",1, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // bloque_codigo ::= INICIO error FIN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_codigo",1, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // lista_sentencias ::= lista_sentencias error sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_sentencias ::= error sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",2, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= VAR ID IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= ID IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= MOSTRAR CADENA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= MOSTRAR ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= LEER ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= SI PARENTESIS_ABIERTO condicion PARENTESIS_CERRADO ENTONCES lista_sentencias FIN SI 
            {
              Object RESULT =null;
		int sleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int sright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Object s = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		
            estructuras.add(new ReporteControl("SI", sleft, String.valueOf(c)));
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= SI error ENTONCES lista_sentencias FIN SI 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= MIENTRAS PARENTESIS_ABIERTO condicion PARENTESIS_CERRADO HACER lista_sentencias FIN MIENTRAS 
            {
              Object RESULT =null;
		int mleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int mright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Object m = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		
            estructuras.add(new ReporteControl("MIENTRAS", mleft, String.valueOf(c)));
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= MIENTRAS error HACER lista_sentencias FIN MIENTRAS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // condicion ::= expresion IGUAL_IGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " == " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // condicion ::= expresion DIFERENTE expresion 
            {
              Object RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " != " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // condicion ::= expresion MENOR expresion 
            {
              Object RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " < " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // condicion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " > " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // condicion ::= expresion MENOR_IGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " <= " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // condicion ::= expresion MAYOR_IGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " >= " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // condicion ::= condicion AND condicion 
            {
              Object RESULT =null;
		int c1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int c1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int c2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int c2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object c2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c1 + " AND " + c2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // condicion ::= condicion OR condicion 
            {
              Object RESULT =null;
		int c1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int c1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int c2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int c2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object c2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c1 + " OR " + c2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // condicion ::= NOT condicion 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = "NOT " + c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // condicion ::= PARENTESIS_ABIERTO condicion PARENTESIS_CERRADO 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = "(" + c + ")"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expresion ::= expresion MAS termino 
            {
              Object RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int opleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int opright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object op = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 
            String occ = e1 + " + " + e2;
            operadores.add(new ReporteOperador("Suma", opleft, opright, occ));
            RESULT = occ; 
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expresion ::= expresion MENOS termino 
            {
              Object RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int opleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int opright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object op = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 
            String occ = e1 + " - " + e2;
            operadores.add(new ReporteOperador("Resta", opleft, opright, occ));
            RESULT = occ; 
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expresion ::= termino 
            {
              Object RESULT =null;
		int tleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object t = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = t; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",5, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // termino ::= termino MULTIPLICADO factor 
            {
              Object RESULT =null;
		int t1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int t1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object t1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int opleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int opright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object op = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int t2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int t2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object t2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 
            String occ = t1 + " * " + t2;
            operadores.add(new ReporteOperador("Multiplicación", opleft, opright, occ));
            RESULT = occ; 
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // termino ::= termino DIVIDIDO factor 
            {
              Object RESULT =null;
		int t1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int t1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object t1 = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int opleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int opright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object op = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int t2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int t2right = ((Symbol)CUP$Parser$stack.peek()).right;
		Object t2 = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 
            String occ = t1 + " / " + t2;
            operadores.add(new ReporteOperador("División", opleft, opright, occ));
            RESULT = occ; 
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // termino ::= factor 
            {
              Object RESULT =null;
		int fleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object f = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",6, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // factor ::= ENTERO 
            {
              Object RESULT =null;
		int eleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((Symbol)CUP$Parser$stack.peek()).right;
		Integer e = (Integer)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = String.valueOf(e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // factor ::= DECIMAL 
            {
              Object RESULT =null;
		int dleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((Symbol)CUP$Parser$stack.peek()).right;
		Double d = (Double)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = String.valueOf(d); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // factor ::= ID 
            {
              Object RESULT =null;
		int idleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = String.valueOf(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // factor ::= PARENTESIS_ABIERTO expresion PARENTESIS_CERRADO 
            {
              Object RESULT =null;
		int eleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object e = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = "(" + e + ")"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",7, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // bloque_config ::= lista_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_config",8, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // lista_config ::= lista_config instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_config",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // lista_config ::= instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_config",9, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // lista_config ::= lista_config error instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_config",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // lista_config ::= error instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_config",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // instruccion_config ::= DEFAULT IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // instruccion_config ::= COLOR_TEXTO_SI IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // instruccion_config ::= COLOR_SI IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // instruccion_config ::= FIGURA_SI IGUAL figura PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // instruccion_config ::= LETRA_SI IGUAL letra PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // instruccion_config ::= LETRA_SIZE_SI IGUAL expresion PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // instruccion_config ::= COLOR_TEXTO_MIENTRAS IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // instruccion_config ::= COLOR_MIENTRAS IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // instruccion_config ::= FIGURA_MIENTRAS IGUAL figura PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // instruccion_config ::= LETRA_MIENTRAS IGUAL letra PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // instruccion_config ::= LETRA_SIZE_MIENTRAS IGUAL expresion PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // instruccion_config ::= COLOR_TEXTO_BLOQUE IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // instruccion_config ::= COLOR_BLOQUE IGUAL color PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // instruccion_config ::= FIGURA_BLOQUE IGUAL figura PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // instruccion_config ::= LETRA_BLOQUE IGUAL letra PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // instruccion_config ::= LETRA_SIZE_BLOQUE IGUAL expresion PIPE expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // color ::= COLOR_HEX 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("color",11, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // color ::= rgb 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("color",11, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // rgb ::= expresion COMA expresion COMA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("rgb",12, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // figura ::= ELIPSE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // figura ::= CIRCULO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // figura ::= PARALELOGRAMO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // figura ::= RECTANGULO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // figura ::= ROMBO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // figura ::= RECTANGULO_REDONDEADO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",13, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // letra ::= ARIAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // letra ::= TIMES_NEW_ROMAN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // letra ::= COMIC_SANS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // letra ::= VERDANA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("letra",14, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    lr_parser CUP$Parser$parser,
    Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
